_PLEASE_PEX_VERSION = "3.0.3"

remote_file(
    name = "please_pex",
    url = f"https://github.com/malonaz/python-rules/releases/download/please_pex-v{_PLEASE_PEX_VERSION}/please_pex-{_PLEASE_PEX_VERSION}-{CONFIG.OS}_{CONFIG.ARCH}",
    binary = True,
    visibility = ["PUBLIC"],
)
